=== SantiGB04/LDM/1er/Ej4_Tres_en_raya/Tres_en_raya.dtd
<!ELEMENT partida (jugadores, tablero, turnos)>
<!ATTLIST partida 
                id ID #REQUIRED
                fecha CDATA #REQUIRED>

<!ELEMENT jugadores (jugador+)>
<!ELEMENT jugador (#PCDATA)>
<!ATTLIST jugador 
            nombre CDATA #REQUIRED
            ficha (X | O) #REQUIRED>

<!ELEMENT tablero (posicion+)>
<!ELEMENT posicion (#PCDATA)>
<!ATTLIST posicion casilla (A1 | A2 | A3 | B1 | B2 | B3 | C1 | C2 | C3) #REQUIRED>

<!ELEMENT turnos (turno+)>
<!ELEMENT turno (#PCDATA)>
<!ATTLIST turno 
            num_turno CDATA #REQUIRED
            jugador CDATA #REQUIRED
            posicion (A1 | A2 | A3 | B1 | B2 | B3 | C1 | C2 | C3) #REQUIRED>

=== SantiGB04/LDM/1er/Ej4_Tres_en_raya/Tres_en_raya.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE partida SYSTEM "Tres_en_raya.dtd">
<partida id="A1" fecha="15/11/2024">
    <jugadores>
        <jugador nombre="Marcelo" ficha="X"/>
        <jugador nombre="Carlos" ficha="O"/>
    </jugadores>
    <tablero>
        <posicion casilla="A1">X</posicion>
        <posicion casilla="B2">O</posicion>
        <posicion casilla="C1">X</posicion>
        <posicion casilla="A2">O</posicion>
    </tablero>
    <turnos>
        <turno num_turno="1" jugador="Marcelo" posicion="A1">X</turno>
        <turno num_turno="2" jugador="Carlos" posicion="B2">O</turno>
        <turno num_turno="3" jugador="Marcelo" posicion="C1">X</turno>
        <turno num_turno="4" jugador="Carlos" posicion="A2">O</turno>
    </turnos>
</partida>
