=== SantiGB04/LDM/1er/EJ5_Curriculum/EjT3_Curriculum.dtd
<!ELEMENT curriculum (datos, formaciones, trabajos, idiomas, habilidades)>
<!ATTLIST curriculum lang (es | en) #REQUIRED>

<!ELEMENT datos (nombre, apellido, nacimiento, direccion, telf, correo, descripcion)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT nacimiento (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT telf (#PCDATA)>
<!ELEMENT correo (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>

<!ELEMENT formaciones (formacion*)>
<!ELEMENT formacion (nombre_form, ano_form, notamedia)>
<!ELEMENT nombre_form (#PCDATA)>
<!ELEMENT ano_form (#PCDATA)>
<!ELEMENT notamedia (#PCDATA)>

<!ELEMENT trabajos (trabajo*)>
<!ELEMENT trabajo (nombre_trab, ano_trab, descripcion_trab, cargo)>
<!ELEMENT nombre_trab (#PCDATA)>
<!ELEMENT ano_trab (#PCDATA)>
<!ELEMENT descripcion_trab (#PCDATA)>
<!ELEMENT cargo (#PCDATA)>

<!ELEMENT idiomas (idioma+)>
<!ELEMENT idioma (nombre_idioma, certificado)>
<!ELEMENT nombre_idioma (#PCDATA)>
<!ELEMENT certificado (#PCDATA) >

<!ELEMENT habilidades (habilidad*)>
<!ELEMENT habilidad (descripcion_habilidad)>
<!ELEMENT descripcion_habilidad (#PCDATA)>

=== SantiGB04/LDM/1er/EJ5_Curriculum/EjT3_Curriculum.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE curriculum SYSTEM "EjT3_Curriculum.dtd">
<curriculum lang="es">
    <datos>
        <nombre>Mohammed Sumbul</nombre>
        <apellido>Serra Puig</apellido>
        <nacimiento>11/09/2001</nacimiento>
        <direccion>Murla 12</direccion>
        <telf>611586912</telf>
        <correo>ASjhfdksdfgjklsbn23@gmail.com</correo>
        <descripcion>Esto es un ejemplo porque no se qué escribir aquí</descripcion>
    </datos>
    <formaciones>
        <formacion>
            <nombre_form>IES Matematic Vicent Caselles Costa</nombre_form>
            <ano_form>1994-1999</ano_form>
            <notamedia>5</notamedia>
        </formacion>
        <formacion>
            <nombre_form>IES Zimbabwe</nombre_form>
            <ano_form>2005-2007</ano_form>
            <notamedia>5</notamedia>
        </formacion>
    </formaciones>

    <trabajos>
        <trabajo>
            <nombre_trab>Burger King</nombre_trab>
            <ano_trab>2006-2018</ano_trab>
            <descripcion_trab>Limpieza de platos</descripcion_trab>
            <cargo>Aseo</cargo>
        </trabajo>
    </trabajos>

    <idiomas>
        <idioma>
            <nombre_idioma>Valencià</nombre_idioma>
            <certificado>C2</certificado>
        </idioma>
    </idiomas>

    <habilidades>
        <habilidad>
            <descripcion_habilidad>Hacer la mandanga</descripcion_habilidad>
        </habilidad>
        <habilidad>
            <descripcion_habilidad>Vender la mandanga</descripcion_habilidad>
        </habilidad>
    </habilidades>

</curriculum>
