=== SantiGB04/LDM/1er/EJ3MinecraftDTD/Minecraft.dtd
<!ELEMENT minecraftItems (item+)>
<!ATTLIST minecraftItems lang (es|en) #REQUIRED>

<!ELEMENT item (name, type, damage?, description)>
<!ATTLIST   item 
            id ID #REQUIRED
            rarity (Comun | Raro | Epico ) #REQUIRED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT damage (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== SantiGB04/LDM/1er/EJ3MinecraftDTD/EjT3_Creacion_Documentos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE minecraftItems SYSTEM "Minecraft.dtd">

<minecraftItems lang="es">
    <item id="A214">
        <name>Pollo Crudo</name>
        <type>Comida</type>
        <rarity>Común</rarity>
        <damage>1</damage>
        <description>Pollo crudo la cual se puede cocinar</description>
    </item>
    <item id="A307">
        <name>Tulipán</name>
        <type>Bloque</type>
        <rarity>Raro</rarity>
        <damage>1</damage>
        <description>Flor rara de algún bioma</description>
    </item>
    <item id="A189">
        <name>Tijeras</name>
        <type>Herramientas</type>
        <rarity>Común</rarity>
        <damage>4</damage>
        <description>Tijeras para cortar lana y otras cosas.</description>
    </item>
    <item id="A999">
        <name>Palo debug</name>
        <type>Arma</type>
        <rarity>Legendario</rarity>
        <damage>1000</damage>
        <description>Palo del debug (No crafteable)</description>
    </item>
    <item id="A723">
        <name>Caña de pescar con zanahoria</name>
        <type>Herramienta</type>
        <rarity>Épico</rarity>
        <damage>5</damage>
        <description>Caña de pescar con zanahoria para ir con un cerdo</description>
    </item>
</minecraftItems>
