=== SantiGB04/LDM/1er/figuras/Figuras.dtd
<!ELEMENT escena (rectangulo*, circunferencia*, linea*)>

<!ELEMENT rectangulo (posicion, altura, ancho)>

<!ELEMENT circunferencia (posicion, radio)>

<!ELEMENT linea (origen, destino)>


<!ELEMENT posicion (#PCDATA)>
<!ELEMENT altura (#PCDATA)>
<!ELEMENT ancho (#PCDATA)>
<!ELEMENT radio (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT destino (#PCDATA)>

=== SantiGB04/LDM/1er/figuras/Figuras.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE escena SYSTEM "Figuras.dtd">

<escena>
    <rectangulo>
        <posicion>150, 400</posicion>
        <altura>120</altura>
        <ancho>150</ancho>
    </rectangulo>

    <circunferencia>
        <posicion>400, 400</posicion>
        <radio>100</radio>
    </circunferencia>
    
    <linea>
        <origen>300, 520</origen>
        <destino>400, 400</destino> 
    </linea>
</escena>
