=== SantiGB04/LDM/1er/BloonsTD6/bloonsgame.dtd
<!ELEMENT bloonsGame (monos, heroes, mapas, bloons, partidas)>
<!ELEMENT monos (mono+)>
<!ELEMENT mono (nombre, precioCompraMono, precioVentaMono, alcance)>
<!ATTLIST   mono idMono ID #REQUIRED 
            categoria (primario | militar | magia | apoyo) #REQUIRED
            velocidadDisparo (lenta | media | rapida | ultrarapida) #REQUIRED>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precioCompraMono (#PCDATA)>
<!ELEMENT precioVentaMono (#PCDATA)>
<!ELEMENT alcance (#PCDATA)>



<!ELEMENT heroes (heroe+)>
<!ELEMENT heroe (nombreHeroe, precioCompraHeroe, precioVentaHeroe, habilidades+, alcance, nivelMax)>
<!ATTLIST heroe idHeroe ID #REQUIRED 
          skin (clasico | alternativo | legendario) #REQUIRED
          velocidadDisparo (lenta | media | rapida | ultrarapida) #REQUIRED>
          
<!ELEMENT nombreHeroe (#PCDATA)>
<!ELEMENT precioCompraHeroe (#PCDATA)>
<!ELEMENT precioVentaHeroe (#PCDATA)>
<!ELEMENT habilidades (habilidad+)>
<!ELEMENT habilidad (#PCDATA)>
<!ATTLIST habilidad     idHabi ID #REQUIRED
                        cooldown CDATA #REQUIRED>

<!ELEMENT nivelMax (#PCDATA)>



<!ELEMENT mapas (mapa+)>
<!ELEMENT mapa (#PCDATA)>
<!ATTLIST mapa idMapa ID #REQUIRED
               nombre CDATA #REQUIRED
               categoriaMapa (facil | medio | dificil) #REQUIRED
               dificultadMapa (facil | medio | dificil | imposible) #REQUIRED
               rondasTotales (40 | 60 | 80 | 100) #REQUIRED
               vidasMapa (150 | 100 | 50 | 1) #REQUIRED
               recompensa (150 | 250 | 500 | 1000) #REQUIRED>




<!ELEMENT bloons (bloon+)>
<!ELEMENT bloon (nombreBloon)>
<!ELEMENT nombreBloon (#PCDATA)>

<!ATTLIST   bloon idBloon ID #REQUIRED
            velocidadMovimiento CDATA #REQUIRED
            vidaBloon CDATA #REQUIRED
            tipoBloon (normal | ceramico | camuflado | moab | emplomado) #REQUIRED>
            



<!ELEMENT partidas (partida+)>
<!ELEMENT partida (estadoPartida, torresColocadas, heroeEnJuego, bloonsEnJuego)>
<!ATTLIST partida   idPartida ID #REQUIRED
                    idMapa IDREF #REQUIRED>
<!ELEMENT estadoPartida (rondaActual, dineroJuego, vidasRestantes)>
<!ELEMENT rondaActual (#PCDATA)>
<!ELEMENT dineroJuego (#PCDATA)>
<!ELEMENT vidasRestantes (#PCDATA)>

<!ELEMENT torresColocadas (torre*)>
<!ELEMENT torre (posicion, ramas*, experiencia*, danyoTorre?, bloonsAcumulado?)>
<!ATTLIST torre idMono IDREF #REQUIRED>


<!ELEMENT posicion (x,y)>
<!ELEMENT x (#PCDATA)>
<!ELEMENT y (#PCDATA)>

<!ELEMENT ramas (rama*)>
<!ELEMENT rama (nombreRama)>
<!ATTLIST rama  nombreRama (A | B | C) #REQUIRED
                nivelRama (1 | 2 | 3 | 4 ) #REQUIRED>
<!ELEMENT nombreRama (#PCDATA)>
<!ELEMENT nivelRama (#PCDATA)>


<!ELEMENT experiencia (#PCDATA)>
<!ELEMENT danyoTorre (#PCDATA)>
<!ELEMENT bloonsAcumulado (#PCDATA)>

<!ELEMENT heroeEnJuego (nivel, experienciaAcumulada, posicion)>
<!ATTLIST heroeEnJuego idHeroe IDREF #REQUIRED>

<!ELEMENT nivel (#PCDATA)>
<!ELEMENT experienciaAcumulada (#PCDATA)>

<!ELEMENT bloonsEnJuego (bloonEnJuego+)>
<!ELEMENT bloonEnJuego (cantidadBloons)>
<!ATTLIST bloonEnJuego  idBloon IDREF #REQUIRED
                        reforzado (si | no) #REQUIRED>
<!ELEMENT cantidadBloons (#PCDATA)>

=== SantiGB04/LDM/1er/BloonsTD6/bloonsgame.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bloonsGame SYSTEM "bloonsgame.dtd">
<bloonsGame>
    <monos>
        <mono idMono="Mono1" categoria="primario" velocidadDisparo="media">
            <nombre>Mono Tirador de Dardos</nombre>
            <precioCompraMono>170</precioCompraMono>
            <precioVentaMono>85</precioVentaMono>
            <alcance>30</alcance>
        </mono>
        <mono idMono="Mono2" categoria="militar" velocidadDisparo="lenta">
            <nombre>Mono Francotirador</nombre>
            <precioCompraMono>350</precioCompraMono>
            <precioVentaMono>175</precioVentaMono>
            <alcance>300</alcance>
        </mono>
        <mono idMono="Mono3" categoria="apoyo" velocidadDisparo="lenta">
            <nombre>Platanar</nombre>
            <precioCompraMono>1200</precioCompraMono>
            <precioVentaMono>700</precioVentaMono>
            <alcance>100</alcance>
        </mono>
    </monos>

    <heroes>
        <heroe idHeroe="He1" skin="clasico" velocidadDisparo="rapida">
            <nombreHeroe>Quincy</nombreHeroe>
            <precioCompraHeroe>800</precioCompraHeroe>
            <precioVentaHeroe>400</precioVentaHeroe>
            <habilidades>
                <habilidad idHabi="HB1" cooldown="40">Lluvia de flechas</habilidad>
                <habilidad idHabi="HB2" cooldown="20">Aumento de velocidad de disparo</habilidad>
            </habilidades>
            <alcance>30</alcance>
            <nivelMax>30</nivelMax>
        </heroe>
        <heroe idHeroe="He2" skin="alternativo" velocidadDisparo="lenta">
            <nombreHeroe>Benjamin</nombreHeroe>
            <precioCompraHeroe>1000</precioCompraHeroe>
            <precioVentaHeroe>500</precioVentaHeroe>
            <habilidades>
                <habilidad idHabi="HB3" cooldown="20">Dar más dinero por tiempo limitado</habilidad>
            </habilidades>
            <alcance>30</alcance>
            <nivelMax>30</nivelMax>
        </heroe>
    </heroes>

    <mapas>
        <mapa idMapa="Mapa1" nombre="Acuario" categoriaMapa="facil" dificultadMapa="dificil" rondasTotales="80" vidasMapa="100" recompensa="500"></mapa> 
        <mapa idMapa="Mapa2" nombre="Volcan" categoriaMapa="dificil" dificultadMapa="imposible" rondasTotales="100" vidasMapa="1" recompensa="1000"></mapa>
    </mapas>
    <bloons>
        <bloon idBloon="Bl1" velocidadMovimiento="10" vidaBloon="10" tipoBloon="normal">
            <nombreBloon>Bloon rojo</nombreBloon>
        </bloon>
        <bloon idBloon="Bl2" velocidadMovimiento="30" vidaBloon="50" tipoBloon="ceramico">
            <nombreBloon>Bloon cerámico</nombreBloon>
        </bloon>
        <bloon idBloon="Bl3" velocidadMovimiento="20" vidaBloon="10" tipoBloon="camuflado">
            <nombreBloon>Bloon camuflado</nombreBloon>
        </bloon>
        <bloon idBloon="Bl4" velocidadMovimiento="20" vidaBloon="500" tipoBloon="moab">
            <nombreBloon>Bloon MOAB</nombreBloon>
        </bloon>
        <bloon idBloon="Bl5" velocidadMovimiento="20" vidaBloon="10" tipoBloon="emplomado">
            <nombreBloon>Bloon emplomado</nombreBloon>
        </bloon>
    </bloons>

    <partidas>
        <partida idPartida="Pa1" idMapa="Mapa1">
            <estadoPartida>
                <rondaActual>45</rondaActual>
                <dineroJuego>3200</dineroJuego>
                <vidasRestantes>68</vidasRestantes>
            </estadoPartida>

            <torresColocadas>
                <torre idMono="Mono1">
                    <posicion>
                        <x>100</x>
                        <y>200</y>
                    </posicion>
                    <ramas>
                        <rama nombreRama="A" nivelRama="2">
                            <nombreRama>Catapulta</nombreRama>
                        </rama>
                        <rama nombreRama="B" nivelRama="3">
                            <nombreRama>Velocidad más rápida</nombreRama>
                        </rama>
                    </ramas>
                    <experiencia>5820</experiencia>
                    <danyoTorre>10</danyoTorre>
                    <bloonsAcumulado>450</bloonsAcumulado>
                </torre>

                <torre idMono="Mono2">
                    <posicion>
                        <x>300</x>
                        <y>150</y>
                    </posicion>
                    <ramas>
                        <rama nombreRama="C" nivelRama="2">
                            <nombreRama>Disparo rápido</nombreRama>
                        </rama>
                    </ramas>
                    <experiencia>5820</experiencia>
                    <danyoTorre>30</danyoTorre>
                    <bloonsAcumulado>160</bloonsAcumulado>
                </torre>

                <torre idMono="Mono3">
                    <posicion>
                        <x>50</x>
                        <y>150</y>
                    </posicion>
                    <ramas>
                        <rama nombreRama="C" nivelRama="4">
                            <nombreRama>Fábrica de platanos</nombreRama>
                        </rama>
                        <rama nombreRama="B" nivelRama="2">
                            <nombreRama>50% más de dinero</nombreRama>
                        </rama>
                    </ramas>
                    <experiencia>4210</experiencia>
                </torre>

            </torresColocadas>
            <heroeEnJuego idHeroe="He1">
                <nivel>6</nivel>
                <experienciaAcumulada>1500</experienciaAcumulada>
                <posicion>
                    <x>50</x>
                    <y>50</y>
                </posicion>
            </heroeEnJuego>
            <bloonsEnJuego>
                <bloonEnJuego idBloon="Bl1" reforzado="no">
                    <cantidadBloons>47</cantidadBloons>
                </bloonEnJuego>
                <bloonEnJuego idBloon="Bl4" reforzado="si">
                    <cantidadBloons>1</cantidadBloons>
                </bloonEnJuego>
                <bloonEnJuego idBloon="Bl5" reforzado="no">
                    <cantidadBloons>10</cantidadBloons>
                </bloonEnJuego>
            </bloonsEnJuego> 
        </partida>
    </partidas>
</bloonsGame>
