=== SantiGB04/LDM/1er/EJ3Mine_Encan_DTD/MinecraftEncan.dtd
<!ELEMENT minecraftItems (item+)>
<!ATTLIST minecraftItems lang (es|en) #REQUIRED>

<!ELEMENT item (name, damage?, description, materials?, wear?, enchantments?)> 



<!ELEMENT id (#PCDATA)>
<!ATTLIST item id ID #REQUIRED
        rarity (Comun | Raro | Epico ) #REQUIRED
        crafteable (true | false) #REQUIRED
        enchantable (true | false) #REQUIRED
        destroyable (true | false) #REQUIRED
        type (bloque | herramienta | arma | entidades) #REQUIRED>



<!ELEMENT name (#PCDATA)>
<!ELEMENT damage (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT wear (#PCDATA)>


<!ELEMENT materials (material+)>
<!ELEMENT material (#PCDATA)>
<!ATTLIST material id ID #REQUIRED>

<!ELEMENT enchantments (enchantment+)>
<!ELEMENT enchantment (#PCDATA)>
<!ATTLIST enchantment id ID #REQUIRED>

=== SantiGB04/LDM/1er/EJ3Mine_Encan_DTD/EjT3_Creacion_Documentos_atributos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE minecraftItems SYSTEM "MinecraftEncan.dtd">

<minecraftItems lang="es">
    <item id="A262" crafteable="true" enchantable="false" rarity="Comun" destroyable="false" type="bloque" >
        <name>Cama</name>
        <damage>1</damage>
        <description>Una simple cama para pasar la noche</description>
        <materials>
            <material id="A221">bloque de madera</material>
            <material id="A892">bloque de lana</material>
        </materials>

    </item>

    <item id="A189" crafteable="true" enchantable="true" rarity="Comun" destroyable="true" type="herramienta">
        <name>Pico de piedra</name>
        <damage>4</damage>
        <description>Pico de piedra para poder minar.</description>
        <materials>
            <material id="A195">bloque de piedra</material>
            <material id="A25">palo</material>
        </materials>
        <enchantments>
            <enchantment id="A502">Irrompibilidad</enchantment>
            <enchantment id="A611">Eficiencia</enchantment>
            <enchantment id="A584">Suerte</enchantment>
        </enchantments>
        <wear>0.2</wear>
    </item>

    <item id="A723" crafteable="true" enchantable="true" rarity="Epico" destroyable="true">
        <name>Ca침a de pe+scar con zanahoria</name>
        <type>Herramienta</type>
        <damage>5</damage>
        <description>Ca침a de pescar con zanahoria para ir con un cerdo</description>
        <materials>
            <material id="A291">ca침a de pescar</material>
            <material id="A443">zanahoria</material>
        </materials>
        <enchantments>
            <enchantment id="A522">Irrompibilidad</enchantment>
            <enchantment id="A498">Reparaci칩n</enchantment>
        </enchantments>
        <wear>0.1</wear>
    </item>
</minecraftItems>
